### ISSUE TITLE
Disappering items

### ISSUE THREAD

**Issue by unafraidzeo** [tewtal/itemrandomizerweb#7] opened 2017-06-13 20:20 UTC
When you go to the area where the morph ball is in a normal non randomize run I would see a different item. However if I would to leave the room and come back the item is gone. So I'm guessing this is a bug in cause if I grab the item first it would trap me in the area due to the not having the morph ball

**Comment by InsaneFirebat** [comment] 2017-06-13 20:28
This is caused by the Zebes Awake flag being set as you make your way to the room on the right. In vanilla, this flag is not set until you make your way up the elevator. The flag causes the Morph Ball room to load in a different state, where there is no item available.

Be sure you always pick up that item before visiting other rooms in Classic Brinstar.

**Comment by tewtal** [comment] 2017-06-14 07:38
I'm going to make a change here if possible and only set the "Zebes Awake" flag if the item at the morph ball location is picked up to prevent this from happening.

**Comment by awilkester** [comment] 2017-07-19 05:55
fixed with the above idea that total had

**Comment by awilkester** [comment] 2017-07-19 05:56
oops

**Closed by awilkester** 2017-07-19 05:56 UTC
Labels: bug
